package com.vitality.clinic.utils.enums;

public enum MedicalSpecialty {
    GASTROENTEROLOGY,
    HEMATOLOGY,
    GYNECOLOGY,
    DERMATOLOGY,
    CARDIOLOGY,
    NEUROLOGY,
    NEPHROLOGY,
    ONCOLOGY,
    ORTHOPEDICS,
    OTORHINOLARYNGOLOGY,
    OPHTHALMOLOGY,
    PEDIATRICS,
    PSYCHIATRY,
    UROLOGY,
    ENDOCRINOLOGY,
}
